export default {
  sign_in: 'LOG IN WITH SINGPASS',
  forgot_pwd: 'Forgot password?',
  rmb_me: 'Remember Me',
  reset_pwd: 'Reset Password',
  new_pwd: 'Enter a new password',
  re_pwd: 'Re-enter new password',
  havenot_acc: "I don't have an account",
  create_acc: 'Create Account',
  created_acc: 'Account Created!',
  created_acc_msg:
    'An email has been sent to your email. \n Please follow the instructions in the email to verify your account.',
  email: 'Email',
  pwd: 'Password',
  sq1: 'Security Question 1:',
  sq2: 'Security Question 2:',
  selectQ: '---Select Question---',
  answer: 'Answer',
  login: 'Login',
  logout: 'Logout',
  continue: 'Continue',
  confirm: 'Confirm',
  submit: 'Submit',
  sign_up: 'Sign up',
  step1: 'Select your avatar',
  step2: 'Enter your name',
  step7: 'I find it easy to build trust among people of diverse backgrounds.',
  email_me: 'Email me',
  lessons: 'Lessons',
  recommend: 'Recommended for you',
  select_courses: 'Select 2 to 3 courses',
  course1: 'Identify Common Grounds & Bridge New Divides',
  course2: 'Embracing and Leading Change',
  course3: 'Do With to Foster Community Ownership',
  course4: 'Growth Mindset',
  view_details: 'View details',
  acceptContinue: 'ACCEPT & CONTINUE',
  next: 'NEXT',
  instruction: 'Instruction',
  explore_homepage: 'EXPLORE HOMEPAGE',

  SDTIntro1: `Hi Pradeesh! I noticed your active involvement in the earlier sessions and felt that you’ve been doing really well!`,
  SDTIntro2: `Now that you’re better equipped with the new skills, you might also be interested to learn more about yourself – so here goes!`,
  SDTIntroModalContent: `Please read the statements carefully and select the best option that describes you in the past 12 months.${'\n\n'}There are no right or wrong answers and your responses will be kept strictly confidential and results will be aggregated.`,

  SDTred1: `In an unfamiliar situation, I will see what has been done well in the past`,
  SDTred2: `We should only share data/information once we are certain that others know what to do with it`,
  SDTred3: `It is more useful to build my own knowledge first in a team`,
  SDTyellow1: `I find it reassuring to seek others' opinions before making a decision`,
  SDTyellow2: `Keeping harmony in the group is important to me`,
  SDTyellow3: `Having familiar faces and friends in the team keeps me going`,
  SDTblue1: `Making practical and realistic decisions is important to me`,
  SDTblue2: `Conflict is acceptable if it means finding a reasonable solution`,
  SDTblue3: `We should consider how the majority feels about an issue rather than an individual`,
  SDTgreen1: `I am motivated by creative discussions and brainstorming`,
  SDTgreen2: `We need to constantly share data and insights as widely as possible`,
  SDTgreen3: `I am happy to work alone when facing problems`,

  completeOnboarding: 'Complete Onboarding',
  completeSDT: 'Complete self-diagnostic test',
  signUpSDT: 'Sign up for recommended training road map courses',
  addAFriend: 'Add a friend',
  smallBonus: 'Complete all narrative BSL - unlock playground',
  mediumBonus: 'Chapter Completion (includes all BSL)',
  superBonus: 'Complete all BSL in app',
  completeEachBSL: 'Complete Each BSL',

  error: 'Error',
  error_network_message:
    'Oh no! Seems like you have a\npoor network connection.\nPlease check your connectivity.',
  retry: 'RETRY',
  error_generic_title: 'Oops!',
  error_generic_message: 'Something went wrong.\nPlease try again',
  error_unreachable_title: 'Server Unreachable',
  error_unreachable_message: 'The server is currently unavailable. Please try again.',
  error_400_title: 'Bad Request',
  error_400_message: 'Missing parameter or bad json format.',
  error_401_title: 'Bad Request',
  error_403_title: 'Forbidden',
  error_403_message: 'Nonce already used.',
  error_404_title: 'Not Found',
  error_404_message: 'Could not find the reward to claim.',
  error_405_title: 'Method Not Allowed',
  error_405_message: 'Method Not Allowed.',
  error_409_title: 'Conflict',
  error_409_message: 'Nickname already used.',
  error_415_title: 'Unsupported Type',
  error_415_message: 'Improper Content Type. It is not set to application/json',
  error_422_title: 'Unprocessable Entity',
  error_422_message: 'Unprocessable entity or invalid parameter.',
  error_500_title: 'Internal Server Error',
  error_500_message: 'Internal server error.',

  xiuPingLastEncounter: `Thank you for your help! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.`,

  greatJob: 'Great Job!',
  noPointBSL: `Learning is a never-ending journey, keep it up!`,
  continueLearning: `Let’s continue learning!`,
  continueLearningTogether: `Let’s continue learning together!`,
  kampungCloser: 'The kampong just got a little closer!',
};
