export default {
  /*ONBOARDING*/
  onboarding_title_1: 'Jelajahi Pengalaman Baru Berkoperasi',
  onboarding_desc_1:
    'Nikmati proses bisnis dan pelayanan optimal melalui aplikasi sellular dan website interaktif.',
  onboarding_title_2: 'Semua Di Satu Tempat',
  onboarding_desc_2: 'Nikmati fitur koperasi modern yang berlimpah dalam satu sistem terpadu. ',
  onboarding_title_3: 'Aman Nyaman Transparan',
  onboarding_desc_3:
    'Data Anggota, Simpanan, Pinjaman, dan Transaksi Bisnis tersistem dapat diakses sewaktu-waktu.',
  /*LOGIN REGISTER*/
  email_textbox_placeholder: 'Email...',
  password_textbox_placeholder: 'Password...',
  popup_lupa_password_title: 'Reset Password',
  popup_lupa_password_desc:
    'Password akan direset menjadi password sementara dan dikirimkan ke emailmu. Gunakan password untuk login, dan ubah password dari setting sesuai keinginan.',
  popup_lupa_password_success_title: 'Reset Berhasil',
  popup_lupa_password_success_desc: 'Cek emailmu untuk melihat password sementara.',

  /* DAFTAR KOPERASI */
  daftar: 'Daftar',
  daftar_koperasi_title_1: 'Apakah koperasimu sudah memiliki akses ke SIKOIN?',
  daftar_koperasi_title_2:
    'Kita lihat dulu yuk bagaimana SIKOIN bisa membawa koperasi mu menjadi koperasi super',
  daftar_koperasi_isi_data_title_1: 'Dapatkan akses masuk ke Smart KoJak hanya dengan 2 langkah ',
  daftar_koperasi_isi_data_title_2:
    'Masukkan emailmu untuk mendapatkan Username & Password sementara',
  daftar_koperasi_isi_data_hint_2:
    'Kamu dapat mengganti Username & Password sewaktu-waktu dari dalam aplikasi SIKOIN.',
  isi_data: 'Isi Data',
  daftar_koperasi_success_1: 'Username & Password sudah dikirim ke',
  daftar_koperasi_success_2:
    'Kamu dapat menggunakan Username & Password tersebut untuk masuk ke aplikasi SIKOIN.',
  masukan_nama_koperasimu: 'Masukkan nama koperasimu...',
  masukan_no_anggota: 'Masukkan NIP',
  masukan_email: 'Masukkan emailmu...',
  cek_inbox: 'Cek Inboxmu ya!',
  daftar_koperasi_failed_title:
    '“Ups, sepertinya koperasimu belum terdaftar, yuk lihat bagaimana Sikoin bisa membawa koperasimu lebih maju',

  /*BUTTON*/
  kembali_ke_login: 'Kembali Ke Login',
  masuk: 'Masuk',
  daftar_ke_koperasimu: 'Daftar Ke Koperasimu',
  lupa_password: 'Lupa Password?',
  tutup: 'Tutup',
  reset: 'Reset',
  belum: 'Belum',
  sudah: 'Sudah',
  ayo: 'Ayo!',
  selanjutnya: 'Selanjutnya',
  pilih_tgl_lahir: 'Pilih Tanggal Lahir',
  kirim_otp_ke_email: 'Kirim OTP Ke Email',
  paham: 'Paham',
  simpan: 'Simpan',
  pilih_dot: 'Pilih...',
  notifikasi: 'Notifikasi',

  /*HOME*/
  beranda: 'Beranda',
  simpanan: 'Simpanan',
  mutasi: 'Mutasi',
  topup: 'Top Up',
  saldo: 'Saldo',
  saldo_belanja: 'Saldo Belanja',
  transfer_antar_simpanan: 'Transfer Antar Simpanan',

  //CHAT
  chat: 'Chat',

  /*MENU*/
  pinjaman: 'Pinjaman',
  transaksi: 'Transaksi',
  market: 'Market',
  voucher: 'Voucher',
  diskon: 'Diskon',
  dokumen: 'Dokumen',

  /*KABAR*/
  kabar: 'Kabar',

  /*PROMO*/
  promo: 'Promo',

  // PINJAMAN
  lanjutkan: 'Lanjutkan',
  ajukan: 'Ajukan',
  masukkan_nominal: 'Masukkan Nominal Pengajuan',
  nominal_pengajuan: 'Nominal Pengajuan Pinjaman',
  nama_lengkap: 'Nama Lengkap',
  nomor_rekening: 'Nomor Rekening',
  nomor_ktp: 'Nomor KTP',
  pinjaman_success_title: 'Selamat, Kamu berhasil mengajukan pinjaman!',
  pinjaman_success_content:
    'Tim kami akan memverifikasi pinjaman Kamu. Dalam waktu 1x24 Jam tim kami akan menghubungi kamu melalui nomor terdaftar dan atau email.',

  /*DOKUMEN*/
  unduh_file: 'Unduh File',
  buka_file: 'Buka File',
  hapus_file: 'Hapus File',
  hapus_file_popup_confirmation_title: 'Kamu akan menghapus salah satu file koperasimu',
  hapus_file_popup_confirmation_content: 'Apa Kamu Yakin?',
  hapus_file_popup_success_title: 'File sudah dihapus dari Dokumen koperasimu',
  tipe: 'Tipe',
  ukuran: 'Ukuran',
  lokasi_file: 'Lokasi File',
  pemilik: 'Pemilik',
  dibuat: 'Dibuat',
  izin: 'Izin',
  yg_memiliki_akses: 'YANG MEMILIKI AKSES',
  umum: 'Umum',
  tertutup: 'Tertutup',
  hapus_akses: 'Hapus Akses',

  /*SALDO SIMPANAN */
  totalSaldo: 'Total Saldo',
  totalSimpanan: 'Total Simpanan',
  penarikan: 'Penarikan',
  pokok: 'Pokok',
  wajib: 'Wajib',
  sukarela: 'Sukarela',
  popup_simpanan_content:
    'Saldo Simpanan digunakan untuk kewajiban berkoperasi. Simpanan tertentu dapat digunakan sebagai alat transaksi pembayaran di dalam SIKOIN.',
  popup_saldo_content: 'Saldo dapat digunakan sebagai alat transaksi pembayaran untuk :',

  // TOPUP
  top_up: 'Top Up',
  pilih_jumlah: 'Pilih Jumlah',
  ketik_manual: 'Ketik Manual',
  simpanan_sukarela: 'Simpanan Sukarela',
  voucher_belanja: 'Voucher Belanja',
  pilih_saldo: 'Pilih saldo yang akan ditop-up',
  pilih_saldo_penarikan: 'Pilih Simpanan yang akan ditarik',
  konfirmasi: 'Konfirmasi',
  ok: 'Ok',
  ok_thumbs: 'Ok 👍',
  popup_topup_title: 'Tenang... semuanya aman!',
  popup_topup_content:
    'Teknologi cloud computing SIKOIN selalu menjaga transaksi & kegiatan berkoperasimu secara real time.',
  jumlah_topup: 'Jumlah Topup',
  untuk_saldo: 'Untuk Saldo',
  rincian: 'Rincian',
  total: 'Total',
  pilih_pembayaran: 'Pilih Metode Pembayaran',
  pembayaran_title_1: 'Silahkan melakukan pembayaran sejumlah',
  pembayaran_title_2: 'ke salah satu rekening di bawah ini',
  topup_success_title: 'Terima kasih atas pembayaran Anda',
  topup_success_content:
    'Tim kami akan memverifikasi pembayaran Kamu. Dalam waktu 1x24 Jam tim kami akan menghubungi kamu melalui nomor terdaftar dan atau email.',
  kembali: 'Kembali',
  penarikan_simpanan: 'Penarikan Simpanan',
  bank_tujuan: 'Bank Tujuan:',
  ajukan_penarikan: 'Ajukan Penarikan',
  penarikan_success_title: 'Terima kasih atas permohonan penarikan Anda',
  penarikan_success_content:
    'Tim kami akan melakukan verifikasi dan memproses penarikan dana Kamu. Tim kami akan menghubungi kamu kembali melalui nomor terdaftar / email / kotak pesan',

  /*MARKET*/
  beli_dgn_voucher: 'Beli Dengan Voucher',
  email: 'Email',
  selengkapnya: 'Selengkapnya',
  favorit: 'Favorit',
  keranjang: 'Keranjang',
  pesanan: 'Pesanan',
  tentang_market: 'Tentang Market',
  kategori: 'Kategori',
  brand: 'Brand',
  toko: 'Toko',
  search_market_placeholder: 'Cari Produk...',
  voucher_toko: 'Voucher Toko',
  kunjungi_toko: 'Kunjungi Toko',
  terbaru: 'Terbaru',
  checkout: 'Checkout',
  variasi: 'Variasi',
  terjual: 'Terjual',
  kondisi: 'Kondisi',
  rating: 'Rating',
  berat: 'Berat',
  asuransi: 'Asuransi',
  warna: 'Warna',
  ubah_variasi: 'Ubah Variasi',
  voucher_toko_tersedia: 'Voucher Toko Tersedia',
  total_harga: 'Total Harga',
  stok: 'Stok',
  jumlah: 'Jumlah',
  lainnya_toko: 'Lainnya Dari Toko Ini',
  alamat_tujuan: 'Alamat Tujuan',
  pengiriman: 'Pengiriman',
  total_pesanan: 'Total Pesanan',
  metode_pembayaran: 'Metode Pembayaran',
  subtotal_produk: 'Subtotal Produk',
  subtotal_pengiriman: 'Subtotal Pengiriman',
  total_pembayaran: 'Total Pembayaran',
  proses_pesanan: 'Proses Pesanan',
  catatan_placeholder: 'Catatan...',
  kembali_ke_beranda: 'Kembali ke Beranda',
  tambahkan_keranjang: 'Tambahkan Ke Keranjang',
  laporkan_produk: 'Laporkan Produk Ini',
  pusat_bantuan: 'Pusat Bantuan',
  market_info_popup: '',

  /*VOUCHER*/
  voucher_center: 'Voucher Center',
  jumlah_voucher: 'Jumlah Voucher',
  harga: 'Harga',
  biaya_admin: 'Biaya Admin',
  voucher_info_popup:
    'Pengelola aplikasi atau Koperasi dapat memiliki toko online milik sendiri. Koperasi dapat menjual produk-produk terbaik secara langsung kepada anggota. Produk-produk yang dijual oleh Koperasi akan muncul di Web dan aplikasi SIKOIN.\n\nSelamat berkoperasi! ☀️',
  snk: 'S&K',
  voucherku: 'Voucher Ku',
  tentang_voucher: 'Tentang Voucher Center',
  batal: 'Batal',
  beli: 'Beli',

  //TRANSAKSI
  unduh_riwayat_transaksi: 'Unduh Riwayat Transaksi',

  // PROFILE
  profile: 'Profile',
  edit_profile: 'Edit Profile',
  menu_profile: 'Menu Profil',
  data_diri: 'Data Diri',
  data_koperasi: 'Data Koperasi',
  pengaturan: 'Pengaturan',
  info_sikoin: 'Tentang SIKOIN',
  nama: 'Nama',
  no_telp: 'No Telp.',
  biodata: 'Biodata',
  ktp: 'KTP',
  referensi_keluarga: 'Referensi Keluarga',
  tanda_tangan: 'Tanda Tangan',
  pekerjaan: 'Pekerjaan',
  identitas_pekerjaan: 'Identitas & Pekerjaan',
  ubah: 'Ubah',
  tidak_jadi: 'Tidak Jadi',
  hapus: 'Hapus',
  dokumen_pendukung: 'Dokumen Pendukung',

  // ALAMAT
  yakin_hapus_alamat: 'Apakah kamu yakin ingin menghapus alamat ini?',
  sukses_hapus_alamat: 'Alamat sudah dihapus',
  daftar_alamat: 'Daftar Alamat',
  tambah_alamat: 'Tambah Alamat',
  ubah_alamat: 'Ubah Alamat',
  judul_alamat: 'Judul Alamat',
  alamat_lengkap: 'Alamat Lengkap',
  rt: 'RT',
  rw: 'RW',
  provinsi: 'Provinsi',
  kabupaten: 'Kabupaten',
  kabupaten_kota: 'Kabupaten / Kota',
  kecamatan: 'Kecamatan',
  kodepos: 'Kode Pos',

  //REFRENSI KELUARGA
  tambah_ref_keluarga: 'Tambah Referensi Keluarga',
  no_ktp: 'Nomor KTP',
  status_ref: 'Status Referensi',

  //KTP
  daftar_ktp: 'Daftar KTP',
  tambah_data_ktp: 'Tambah Data KTP',
  ubah_data_ktp: 'Ubah Data KTP Ku',
  ubah_ktp: 'Ubah KTP',
  tambah_ktp: 'Tambah KTP',

  //BIODATA
  tempat_lahir: 'Tempat Lahir',
  tgl_lahir: 'Tanggal Lahir',
  jenis_kelamin: 'Jenis Kelamin',
  gol_darah: 'Gol. Darah',
  kewarganegaraan: 'Kewarganegaraan',
  pendidikan_terakhir: 'Pendidikan Terakhir',
  agama: 'Agama',
  status_pernikahan: 'Status Pernikahan',
  jumlah_anak: 'Jumlah Anak',
  detail_pekerjaan: 'Detail Pekerjaan',
  golongan_darah: 'Golongan Darah',
  edit_biodata: 'Edit Biodata',
  tambah_biodata: 'Tambah Biodata',

  //PEKERJAAN
  tambah_pekerjaan: 'Tambah Data Pekerjaan',
  edit_pekerjaan: 'Edit Data Pekerjaan',
  gaji_bulanan: 'Gaji Bulanan',
  gaji_penghasilan_bulanan: 'Gaji / Penghasilan Bulanan',
  masa_kerja: 'Masa Kerja',
  gaji_pokok: 'Gaji Pokok',
  rekening: 'Rekening',
  no_rekening: 'Nomor Rekening',
  nama_perusahaan: 'Nama Perusahaan / PT',
  alamat_kantor: 'Alamat Kantor / Perusahaan',
  provinsi_kota: 'Provinsi / Kota',
  masa_kerja_tahun: 'Masa Kerja (Tahun)',
  masa_kerja_bulan: 'Masa Kerja (Bulan)',
  bank: 'Bank',
  jabatan_terakhir: 'Jabatan Terakhir',

  //DATA KOPERASI
  nama_koperasi: 'Nama Koperasi',
  no_badan_hukum: 'No. Badan Hukum',
  alamat: 'Alamat',
  website: 'Website',

  //VALIDATION
  tidak_boleh_kosong: 'Tidak Boleh Kosong',
  format: 'Format',
  salah: 'Salah',
  password: 'Password',

  error: 'Error',
  error_network_message:
    'Oh no! Seems like you have a\npoor network connection.\nPlease check your connectivity.',
  retry: 'RETRY',
  error_generic_title: 'Oops!',
  error_generic_message: 'Ada Kesalahan.\nMohon dicoba kembali',
  error_unreachable_title: 'Server Unreachable',
  error_unreachable_message: 'The server is currently unavailable. Please try again.',
  error_400_title: 'Bad Request',
  error_400_message: 'Missing parameter or bad json format.',
  error_401_title: 'Bad Request',
  error_403_title: 'Forbidden',
  error_403_message: 'Nonce already used.',
  error_404_title: 'Not Found',
  error_404_message: 'Could not find the reward to claim.',
  error_405_title: 'Method Not Allowed',
  error_405_message: 'Method Not Allowed.',
  error_409_title: 'Conflict',
  error_409_message: 'Nickname already used.',
  error_415_title: 'Unsupported Type',
  error_415_message: 'Improper Content Type. It is not set to application/json',
  error_422_title: 'Unprocessable Entity',
  error_422_message: 'Unprocessable entity or invalid parameter.',
  error_500_title: 'Internal Server Error',
  error_500_message: 'Internal server error.',
};
