export const SHOW_ERROR_MODAL = 'SHOW_ERROR_MODAL';
export const CLOSE_ERROR_MODAL = 'CLOSE_ERROR_MODAL';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';

export const SET_EMAIL = 'SET_EMAIL';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const DELETE_ALAMAT = 'DELETE_ALAMAT';
export const ADD_ALAMAT = 'ADD_ALAMAT';
export const UPDATE_ALAMAT = 'UPDATE_ALAMAT';

export const ADD_KELUARGA = 'ADD_KELUARGA';
export const UPDATE_KELUARGA = 'UPDATE_KELUARGA';
export const DELETE_KELUARGA = 'DELETE_KELUARGA';
